INSERT INTO Usuario VALUES
	('jvitorfromhell', 'Jose Vitor Schneid', 'jvitor.schneid@gmail.com'),
    ('anaLegs', 'Ana Pernas', 'anaLegs@inf.ufpel.edu.br'),
    ('bubbles', 'Thiago Bubolz', 'bubbles@hotmail.com'),
    ('freitas', 'Matheus Freitag', 'freitascoms@bol.com.br'),
    ('yanyantcha', 'Yan Soares', 'yanyantcha@msn.com'),
    ('leozerah', 'Leo Lima', 'vamotricolor@yahoo.com.br');
    
INSERT INTO Formato VALUES
	('Standard', 60),
    ('Modern', 60),
    ('Legacy', 60),
    ('Pauper', 60),
    ('Commander', 100);
    
INSERT INTO Bloco VALUES
	('LEA', 'Limited Edition Alpha'),
    ('LEB', 'Limited Edition Beta'),
    ('2ED', 'Unlimited'),
    ('3ED', 'Revised Edition'),
    ('4ED', 'Fourth Edition'),
    ('5ED', 'Fifth Edition'),
    ('6ED', 'Sixth Edition'),
    ('7ED', 'Seventh Edition'),
    ('8ED', 'Eighth Edition'),
    ('9ED', 'Ninth Edition'),
    ('10E', 'Tenth Edition'),
    ('M10', 'Magic 2010'),
    ('M11', 'Magic 2011'),
    ('M12', 'Magic 2012'),
    ('M13', 'Magic 2013'),
    ('M14', 'Magic 2014'),
    ('M15', 'Magic 2015'),
    ('ORI', 'Magic Origins'),
    ('ARN', 'Arabian Nights'),
    ('ATQ', 'Antiquities'),
    ('LEG', 'Legends'),
    ('DRK', 'The Dark'),
    ('FEM', 'Fallen Empires'),
    ('HML', 'Homelands'),
    ('ICE', 'Ice Age'),
    ('ALL', 'Alliances'),
    ('CSP', 'Coldsnap'),
    ('MIR', 'Mirage'),
    ('VIS', 'Visions'),
    ('WTH', 'Weatherlight'),
    ('TMP', 'Tempest'),
    ('STH', 'Stronghold'),
    ('EXO', 'Exodus'),
    ('USG', "Urza's Saga"),
    ('ULG', "Urza's Legacy"),
    ('UDS', "Urza's Destiny"),
    ('MMQ', 'Mercadian Masques'),
    ('NMS', 'Nemesis'),
    ('PCY', 'Prophecy'),
    ('INV', 'Invasion'),
    ('PLS', 'Planeshift'),
    ('APC', 'Apocalipse'),
    ('ODY', 'Odissey'),
    ('TOR', 'Torment'),
    ('JUD', 'Judgement'),
    ('ONS', 'Onslaught'),
    ('LGN', 'Legions'),
    ('SCG', 'Scourge'),
    ('MRD', 'Mirrodin'),
    ('DST', 'Darksteel'),
    ('5DN', 'Fifth Dawn'),
    ('CHK', 'Champions of Kamigawa'),
    ('BOK', 'Betrayors of Kamigawa'),
    ('SOK', 'Saviors of Kamigawa'),
    ('RAV', 'Ravnica: City of Guilds'),
    ('GPT', 'Guildpact'),
    ('DIS', 'Dissension'),
    ('TSP', 'Time Spiral'),
    ('PLC', 'Planar Chaos'),
    ('FUT', 'Future Sight'),
    ('LRW', 'Lorwyn'),
    ('MOR', 'Morningtide'),
    ('SHM', 'Shadowmoor'),
    ('EVE', 'Eventide'),
    ('ALA', 'Shards of Alara'),
    ('CON', 'Conflux'),
    ('ARB', 'Alara Reborn'),
    ('ZEN', 'Zendikar'),
    ('WWK', 'Worldwake'),
    ('ROE', 'Rise of Eldrazi'),
    ('SOM', 'Scars of Mirrodin'),
    ('MBS', 'Mirrodin Besieged'),
    ('NPH', 'New Phyrexia'),
    ('ISD', 'Innistrad'),
    ('DKA', 'Dark Ascension'),
    ('AVR', 'Avacyn Restored'),
    ('RTR', 'Return to Ravnica'),
    ('GTC', 'Gatecrash'),
    ('DGM', "Dragon's Maze"),
    ('THS', 'Theros'),
    ('BNG', 'Born of the Gods'),
    ('JOU', 'Journey into Nyx'),
    ('KTK', 'Khans of Tarkir'),
    ('FRF', 'Fate Reforged'),
    ('DTK', 'Dragons of Tarkir'),
    ('BFZ', 'Battle for Zendikar'),
    ('OGW', 'Oath of the Gatewatch'),
    ('SOI', 'Shadows over Innistrad'),
    ('EMN', 'Eldritch Moon'),
    ('KLD', 'Kaladesh'),
    ('AER', 'Aether Revolt'),
    ('MMA', 'Modern Masters'),
    ('MM2', 'Modern Masters 2015'),
    ('EMA', 'Eternal Masters');

INSERT INTO Carta VALUES
	('Forest', 'Basic Land', 'C', 0),
    ('Mountain', 'Basic Land', 'C', 0),
    ('Swamp', 'Basic Land', 'C', 0),
    ('Island', 'Basic Land', 'C', 0),
    ('Plains', 'Basic Land', 'C', 0),
    ('', '', '', ),
    ('', '', '', ),
    ('', '', '', ),
    ('', '', '', ),
    ('', '', '', ),
    ('', '', '', ),
    ('', '', '', ),
    ('', '', '', ),
    ('', '', '', ),
    ('', '', '', ),
    ('', '', '', ),
    ('', '', '', ),
    ('', '', '', ),
    ('', '', '', ),
    ('', '', '', ),
    ('', '', '', ),
    ('', '', '', ),
    ('', '', '', ),
    ('', '', '', ),
    ('', '', '', ),
    ('', '', '', ),
    ('', '', '', ),
    ('', '', '', ),
    ('', '', '', ),
    ('', '', '', ),
    ('', '', '', ),
    ('', '', '', ),
    ('', '', '', ),
    ('', '', '', ),
    ('', '', '', ),
    ('', '', '', ),
    ('', '', '', ),
    ('', '', '', ),
    ('', '', '', ),
    ('', '', '', ),
    ('', '', '', ),
    ('', '', '', ),
    ('', '', '', ),
    ('', '', '', ),
    ('', '', '', ),
    ('', '', '', ),
    ('', '', '', ),
    ('', '', '', ),
    ('', '', '', ),
    ('', '', '', ),
    ('', '', '', );

INSERT INTO Armazenamento (dono, tipo, limite) VALUES
	('jvitorfromhell', 'Pasta', 180),
    ('anaLegs', 'Pasta', 180);
    
INSERT INTO CopiaCarta (nomeCarta, Usuario, Armazenamento) VALUES
	('Floresta', 'jvitorfromhell', 1),
    ('Floresta', 'anaLegs', 2);